# This file was generated by GoReleaser. DO NOT EDIT.
cask "playlist" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "44f14b34ff16d13a9c3456a7966abc46ccfc28f3ee35b7c9bb0486967a8adf56"
      url "https://github.com/jonaaldas/playlist/releases/download/v#{version}/playlist_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca61fe2540a953a58b85b2cb3e77b51d45e4f98c569e447737b0b68e251b8986"
      url "https://github.com/jonaaldas/playlist/releases/download/v#{version}/playlist_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f660a7dd99f7193a3cd6451ab3803c6431eb7d19a367d390e8589e3081c72243"
      url "https://github.com/jonaaldas/playlist/releases/download/v#{version}/playlist_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "60f5740c7394e5b2d61d5cc544cc1cd3089f0911664775112cf1e74b2f0ab6d3"
      url "https://github.com/jonaaldas/playlist/releases/download/v#{version}/playlist_#{version}_linux_arm64.tar.gz"
    end
  end

  name "playlist"
  desc "Transfer playlists between Spotify and Apple Music, in either direction."
  homepage "https://github.com/jonaaldas/playlist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "playlist"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/playlist"]
    end
  end

  # No zap stanza required

end
